on:
  push:
  pull_request:


name: Lint
jobs:
  gofmt:
    name: gofmt
    runs-on: ubuntu-latest
    defaults:
      working-directory: backend
      run:
        working-directory: backend
      setup-go:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        id: setup-go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Check Go Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
